name: Deploy FastAPI Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          username: ec2-user
          script: |
            echo "Starting deployment..."
            
            # Navigate to project directory
            cd /home/ec2-user/fastapi-book-project
            
            # Fetch and reset to main
            echo "Fetching latest changes..."
            git fetch origin main
            
            echo "Resetting to origin/main..."
            git reset --hard origin/main
            
            # Setup virtual environment
            echo "Setting up virtual environment..."
            python3 -m venv venv || exit 1
            source venv/bin/activate || exit 1
            
            # Install dependencies
            echo "Installing dependencies..."
            pip install -r requirements.txt || exit 1
            
            # Restart services
            echo "Restarting services..."
            sudo systemctl restart fastapi
            sudo systemctl restart nginx
            
            # Verify deployment
            echo "Verifying deployment..."
            sudo systemctl status fastapi
            sudo systemctl status nginx