name: Deploy FastAPI Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}  # Reuse your existing secret
          key: ${{ secrets.EC2_SSH_KEY }}     # Reuse your existing secret
          username: ec2-user                  # Your existing EC2 username
          script: |
            echo "Starting deployment..."
            
            # Create and navigate to project directory
            cd /home/ec2-user/fastapi-book-project
            
            # Pull latest changes
            echo "Pulling latest changes..."
            git fetch --all
            git pull origin main
            
            # Setup virtual environment
            echo "Setting up virtual environment..."
            python3 -m venv venv || exit 1
            source venv/bin/activate || exit 1
            
            # Install FastAPI
            echo "Installing FastAPI..."
            pip install fastapi || exit 1
            
            # Install dependencies
            echo "Installing dependencies..."
            pip install -r requirements.txt || exit 1
            
            # Stop existing application
            echo "Stopping existing application..."
            sudo systemctl stop fastapi || echo "No existing service found"
            
            # Start application
            echo "Starting application..."
            sudo systemctl start fastapi
            echo "Application started successfully"
            
            # Verify deployment
            echo "Verifying deployment..."
            sudo systemctl status fastapi
